CREATE DATABASE FILE_EX;
		
USE FILE_EX;
		
CREATE TABLE FILE (
	USER_NAME 		     VARCHAR(30),
	TITLE 			 	 VARCHAR(50),
	ORIGINAL_FILE_NAME   VARCHAR(256),
	FILESYSTEM_NAME		 VARCHAR(256),
	CONTENT_TYPE 		 VARCHAR(256),
	LENGTH				 LONG,
	FILE_UPLOAD_DATE     DATE
	);

SELECT * FROM FILE;